package com.smartrent.config;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.FieldDefaults;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

/**
 * SePay payment gateway configuration.
 *
 * <p>SePay (https://sepay.vn) is not a hosted-checkout gateway. It is a bank-transfer
 * reconciliation service: the customer transfers money to your bank account via a VietQR
 * code, and SePay calls your {@code webhook} the moment a matching transfer lands.
 *
 * <ul>
 *   <li>The VietQR image is generated by URL ({@code https://qr.sepay.vn/img}) - no API call.</li>
 *   <li>Each pending order embeds a unique {@code codePrefix + random} string in the transfer
 *       content so the incoming webhook can be matched back to the order.</li>
 *   <li>The webhook is authenticated with an {@code Authorization: Apikey <apiKey>} header.</li>
 * </ul>
 */
@Getter
@Setter
@Configuration
@ConfigurationProperties(prefix = "sepay")
@FieldDefaults(level = AccessLevel.PRIVATE)
public class SePayConfig {

    /** SePay Merchant ID (your SePay account/channel identifier). */
    String merchantId;

    /**
     * SePay Secret Key. SePay sends it back to us in the IPN/webhook's
     * {@code Authorization: Apikey <secretKey>} header, which we verify before trusting the payload.
     */
    String secretKey;

    /** IPN / webhook URL SePay calls when a matching transfer is detected (informational). */
    String ipnUrl;

    /** Receiving bank account number. */
    String accountNumber;

    /** Bank short name as used by VietQR / SePay (e.g. MBBank, Vietcombank, ACB, TPBank). */
    String bankCode;

    /** Account holder name (display only). */
    String accountName;

    /** Base URL for the SePay dynamic VietQR image. */
    String qrBaseUrl = "https://qr.sepay.vn/img";

    /** Prefix prepended to the per-order transfer code (uppercase alphanumerics only). */
    String codePrefix = "SR";

    /** How long the QR / payment window is shown to the user, in minutes. */
    Integer expiryMinutes = 15;
}
