package com.smartrent.service.payment.provider;

import com.smartrent.config.SePayConfig;
import com.smartrent.constants.PricingConstants;
import com.smartrent.dto.request.PaymentRequest;
import com.smartrent.dto.response.PaymentCallbackResponse;
import com.smartrent.dto.response.PaymentResponse;
import com.smartrent.enums.PaymentProvider;
import com.smartrent.enums.TransactionStatus;
import com.smartrent.infra.repository.PaymentRepository;
import com.smartrent.infra.repository.TransactionAuditRepository;
import com.smartrent.infra.repository.entity.Transaction;
import com.smartrent.utility.PaymentUtil;
import jakarta.servlet.http.HttpServletRequest;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * SePay Payment Provider Implementation.
 *
 * <p>Flow overview:
 * <ol>
 *   <li>{@link #createPayment} generates a unique transfer code ({@code codePrefix + random}),
 *       stores it on the transaction ({@code sepay_code=<CODE>} in {@code additionalInfo}), and
 *       returns a dynamic VietQR image URL pre-filled with the receiving account, amount and that
 *       code. No external API call is needed - the QR is generated by URL.</li>
 *   <li>The customer transfers the exact amount with that code in the transfer content.</li>
 *   <li>SePay calls the webhook ({@code POST /v1/payments/webhook/sepay}, authenticated with
 *       {@code Authorization: Apikey <apiKey>}). {@link #processIPN} extracts the code from the
 *       webhook's {@code code}/{@code content}, finds the pending transaction, checks the amount,
 *       and marks it COMPLETED.</li>
 * </ol>
 *
 * <p>There is no redirect / cancel page: the frontend renders the QR, shows the bank details, and
 * polls {@code GET /v1/payments/transactions/{txnRef}} until the status leaves {@code PENDING}.
 */
@Slf4j
@Service
public class SePayPaymentProvider extends AbstractPaymentProvider {

    private final SePayConfig sePayConfig;

    private static final ZoneId VIETNAM_ZONE = ZoneId.of("Asia/Ho_Chi_Minh");
    private static final Pattern SEPAY_CODE_PATTERN = Pattern.compile("sepay_code=([A-Z0-9]+)");

    public SePayPaymentProvider(PaymentRepository paymentRepository,
                                TransactionAuditRepository transactionAuditRepository,
                                SePayConfig sePayConfig) {
        super(paymentRepository, transactionAuditRepository);
        this.sePayConfig = sePayConfig;
    }

    @Override
    public PaymentProvider getProviderType() {
        return PaymentProvider.SEPAY;
    }

    @Override
    public PaymentResponse createPayment(PaymentRequest request, HttpServletRequest httpRequest) {
        log.info("Creating SePay payment for request: {}", request.getOrderInfo());

        if (!validateConfiguration()) {
            throw new RuntimeException("SePay configuration is incomplete. Please set SEPAY_SECRET_KEY");
        }

        Transaction transaction = createPaymentRecord(request, httpRequest);
        LocalDateTime createdAt = transaction.getCreatedAt() != null
                ? transaction.getCreatedAt() : LocalDateTime.now(VIETNAM_ZONE);

        // Never re-issue a QR for an already finalized transaction.
        if (transaction.getStatus() != TransactionStatus.PENDING) {
            log.info("Transaction {} is already {}, returning without issuing a new SePay QR",
                    transaction.getTransactionId(), transaction.getStatus());
            return PaymentResponse.builder()
                    .transactionRef(transaction.getTransactionId())
                    .provider(PaymentProvider.SEPAY)
                    .amount(transaction.getAmount())
                    .currency(PricingConstants.DEFAULT_CURRENCY)
                    .orderInfo(transaction.getOrderInfo())
                    .createdAt(createdAt)
                    .build();
        }

        // Reuse an existing code if this transaction was already initiated (idempotent QR).
        String code = extractCode(transaction);
        if (code == null) {
            code = generateCode();
            String currentInfo = transaction.getAdditionalInfo() != null ? transaction.getAdditionalInfo() : "";
            transaction.setAdditionalInfo(currentInfo + " | sepay_code=" + code);
            paymentRepository.save(transaction);
        }

        long amount = request.getAmount().longValue();
        // In sandbox you simulate transfers from the SePay dashboard, so a receiving bank account is
        // optional - only build the (scannable) VietQR when an account number is configured.
        String qrUrl = isBlank(sePayConfig.getAccountNumber()) ? null : buildQrUrl(amount, code);
        if (qrUrl == null) {
            log.info("SePay account number not configured; returning transfer code without a VietQR (sandbox mode). code={}", code);
        }

        int expiryMinutes = sePayConfig.getExpiryMinutes() != null ? sePayConfig.getExpiryMinutes() : 15;

        Map<String, Object> providerData = new HashMap<>();
        providerData.put("accountNumber", sePayConfig.getAccountNumber());
        providerData.put("bankCode", sePayConfig.getBankCode());
        providerData.put("accountName", sePayConfig.getAccountName());
        providerData.put("amount", amount);
        providerData.put("transferContent", code);
        providerData.put("qrUrl", qrUrl);

        return PaymentResponse.builder()
                .transactionRef(transaction.getTransactionId())
                .paymentUrl(qrUrl)
                .qrCodeData(qrUrl)
                .provider(PaymentProvider.SEPAY)
                .amount(request.getAmount())
                .currency(PricingConstants.DEFAULT_CURRENCY)
                .orderInfo(transaction.getOrderInfo())
                .providerData(providerData)
                .createdAt(createdAt)
                .expiresAt(createdAt.plusMinutes(expiryMinutes))
                .build();
    }

    @Override
    public PaymentCallbackResponse processIPN(Map<String, String> params, HttpServletRequest httpRequest) {
        log.info("Processing SePay webhook. Keys: {}", params.keySet());

        String transferType = firstNonBlank(params.get("transferType"));
        // Only incoming transfers settle an order; ignore outgoing ones (still ack with 200 upstream).
        if (transferType != null && !"in".equalsIgnoreCase(transferType)) {
            return failure(null, "SEPAY_IGNORED_TRANSFER_TYPE_" + transferType, true);
        }

        Optional<Transaction> txOpt = findTransactionByCode(params);
        if (txOpt.isEmpty()) {
            log.warn("No pending transaction matched SePay webhook. code={}, content={}",
                    params.get("code"), params.get("content"));
            return failure(null, "SEPAY_ORDER_NOT_FOUND", true);
        }
        Transaction transaction = txOpt.get();

        String providerTxnId = firstNonBlank(params.get("id"));
        String referenceCode = firstNonBlank(params.get("referenceCode"));
        String gateway = firstNonBlank(params.get("gateway"), "SEPAY");

        // Idempotency: a webhook may be delivered more than once.
        if (transaction.getStatus() == TransactionStatus.COMPLETED) {
            log.info("SePay transaction {} already COMPLETED, acknowledging duplicate webhook",
                    transaction.getTransactionId());
            return success(transaction, providerTxnId);
        }

        BigDecimal transferred = parseAmount(params.get("transferAmount"));
        BigDecimal expected = transaction.getAmount();
        if (transferred == null || (expected != null && transferred.compareTo(expected) < 0)) {
            log.warn("SePay amount mismatch for {}. expected={}, transferred={}",
                    transaction.getTransactionId(), expected, transferred);
            return PaymentCallbackResponse.builder()
                    .provider(PaymentProvider.SEPAY)
                    .transactionRef(transaction.getTransactionId())
                    .status(transaction.getStatus())
                    .amount(expected)
                    .currency(PricingConstants.DEFAULT_CURRENCY)
                    .success(false)
                    .signatureValid(true)
                    .message("SEPAY_AMOUNT_MISMATCH")
                    .build();
        }

        updatePaymentWithProviderData(
                transaction.getTransactionId(),
                providerTxnId,
                "BANK_TRANSFER",
                gateway,
                referenceCode,
                TransactionStatus.COMPLETED,
                "00",
                "Success"
        );

        return success(transaction, providerTxnId);
    }

    @Override
    public PaymentCallbackResponse queryTransaction(String transactionRef) {
        log.info("Querying SePay transaction: {}", transactionRef);
        Optional<Transaction> txOpt = findPaymentByTransactionRef(transactionRef);
        if (txOpt.isEmpty()) {
            return PaymentCallbackResponse.builder()
                    .provider(PaymentProvider.SEPAY)
                    .transactionRef(transactionRef)
                    .success(false)
                    .message("Transaction not found")
                    .build();
        }
        Transaction transaction = txOpt.get();
        // SePay has no per-order status API; the webhook is the source of truth, so report the DB state.
        return PaymentCallbackResponse.builder()
                .provider(PaymentProvider.SEPAY)
                .transactionRef(transactionRef)
                .providerTransactionId(transaction.getProviderTransactionId())
                .status(transaction.getStatus())
                .amount(transaction.getAmount())
                .currency(PricingConstants.DEFAULT_CURRENCY)
                .success(transaction.getStatus() == TransactionStatus.COMPLETED)
                .signatureValid(true)
                .message("Transaction status retrieved from database")
                .build();
    }

    @Override
    public boolean validateSignature(Map<String, String> params, String signature) {
        // SePay authenticates the webhook via the Authorization: Apikey header (verified in the
        // controller), not via a body signature.
        return true;
    }

    @Override
    public boolean cancelPayment(String transactionRef, String reason) {
        log.info("Cancelling SePay payment: {} - Reason: {}", transactionRef, reason);
        try {
            updatePaymentStatus(transactionRef, TransactionStatus.CANCELLED, "CANCELLED",
                    reason != null ? reason : "Cancelled by user");
            return true;
        } catch (Exception e) {
            log.error("Error cancelling SePay payment: {}", transactionRef, e);
            return false;
        }
    }

    @Override
    public PaymentCallbackResponse refundPayment(String transactionRef, String amount, String reason) {
        log.info("Refund requested for SePay payment: {} - Amount: {}", transactionRef, amount);
        return PaymentCallbackResponse.builder()
                .provider(PaymentProvider.SEPAY)
                .transactionRef(transactionRef)
                .message("Refund is not supported for SePay bank transfers; refund manually from your bank")
                .success(false)
                .build();
    }

    @Override
    public boolean supportsFeature(PaymentFeature feature) {
        return switch (feature) {
            case QR_CODE, BANK_TRANSFER -> true;
            default -> false;
        };
    }

    @Override
    public Map<String, Object> getConfigurationSchema() {
        Map<String, Object> schema = new HashMap<>();
        schema.put("provider", "SePay");
        schema.put("merchantId", sePayConfig.getMerchantId());
        schema.put("accountNumber", sePayConfig.getAccountNumber());
        schema.put("bankCode", sePayConfig.getBankCode());
        schema.put("accountName", sePayConfig.getAccountName());
        schema.put("qrBaseUrl", sePayConfig.getQrBaseUrl());
        schema.put("currency", PricingConstants.DEFAULT_CURRENCY);
        schema.put("expiryMinutes", sePayConfig.getExpiryMinutes());
        return schema;
    }

    @Override
    public boolean validateConfiguration() {
        // The Secret Key is the only hard requirement: it authenticates the incoming IPN/webhook,
        // which is what actually settles payments. The bank account is only needed to render a
        // scannable VietQR for real (non-sandbox) transfers.
        if (isBlank(sePayConfig.getSecretKey())) {
            log.error("SePay Secret Key is not configured");
            return false;
        }
        if (isBlank(sePayConfig.getAccountNumber())) {
            log.warn("SePay account number is not configured - VietQR will be omitted (OK for sandbox/dashboard simulation)");
        }
        return true;
    }

    // ---------------------------------------------------------------------
    // Private helpers
    // ---------------------------------------------------------------------

    private String buildQrUrl(long amount, String code) {
        String acc = encode(sePayConfig.getAccountNumber());
        String bank = encode(sePayConfig.getBankCode());
        String des = encode(code);
        return sePayConfig.getQrBaseUrl()
                + "?acc=" + acc
                + "&bank=" + bank
                + "&amount=" + amount
                + "&des=" + des;
    }

    /**
     * Find the pending transaction referenced by a SePay webhook. Banks may upper-case and strip
     * separators from the transfer content, so we try the dedicated {@code code} field first and
     * then every alphanumeric token in {@code content}.
     */
    private Optional<Transaction> findTransactionByCode(Map<String, String> params) {
        Set<String> candidates = new LinkedHashSet<>();
        addCandidate(candidates, params.get("code"));
        String content = params.get("content");
        if (content != null) {
            for (String token : content.split("[^A-Za-z0-9]+")) {
                addCandidate(candidates, token);
            }
        }
        for (String candidate : candidates) {
            Optional<Transaction> tx = paymentRepository.findByAdditionalInfoContaining("sepay_code=" + candidate);
            if (tx.isPresent()) {
                return tx;
            }
        }
        return Optional.empty();
    }

    private void addCandidate(Set<String> candidates, String raw) {
        if (raw == null) {
            return;
        }
        String normalized = raw.trim().toUpperCase();
        // Our codes are prefix + 8 alphanumerics; ignore obviously-too-short tokens.
        if (normalized.length() >= 4 && normalized.matches("[A-Z0-9]+")) {
            candidates.add(normalized);
        }
    }

    private String generateCode() {
        String prefix = sePayConfig.getCodePrefix() != null ? sePayConfig.getCodePrefix() : "SR";
        return (prefix + PaymentUtil.generateRandomString(8)).toUpperCase();
    }

    private String extractCode(Transaction transaction) {
        String info = transaction.getAdditionalInfo();
        if (info == null) {
            return null;
        }
        Matcher matcher = SEPAY_CODE_PATTERN.matcher(info);
        String last = null;
        while (matcher.find()) {
            last = matcher.group(1);
        }
        return last;
    }

    private PaymentCallbackResponse success(Transaction transaction, String providerTxnId) {
        return PaymentCallbackResponse.builder()
                .provider(PaymentProvider.SEPAY)
                .transactionRef(transaction.getTransactionId())
                .providerTransactionId(providerTxnId)
                .status(TransactionStatus.COMPLETED)
                .amount(transaction.getAmount())
                .currency(PricingConstants.DEFAULT_CURRENCY)
                .responseCode("00")
                .success(true)
                .signatureValid(true)
                .message("Payment successful")
                .build();
    }

    private PaymentCallbackResponse failure(String ref, String message, boolean signatureValid) {
        return PaymentCallbackResponse.builder()
                .provider(PaymentProvider.SEPAY)
                .transactionRef(ref)
                .status(TransactionStatus.FAILED)
                .success(false)
                .signatureValid(signatureValid)
                .message(message)
                .build();
    }

    private BigDecimal parseAmount(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        try {
            return new BigDecimal(value.trim());
        } catch (NumberFormatException e) {
            log.warn("Unable to parse SePay transferAmount: {}", value);
            return null;
        }
    }

    private String encode(String value) {
        return value == null ? "" : URLEncoder.encode(value, StandardCharsets.UTF_8);
    }

    private boolean isBlank(String value) {
        return value == null || value.isBlank();
    }

    private String firstNonBlank(String... values) {
        if (values == null) {
            return null;
        }
        for (String value : values) {
            if (value != null && !value.isBlank()) {
                return value;
            }
        }
        return null;
    }
}
