# Spring Cloud compatibility
spring:
  cloud:
    compatibility-verifier:
      enabled: false

# VNPay Configuration (Local Development - using sandbox/test values)
vnpay:
  tmn-code: "${VNPAY_TMN_CODE:TESTCODE}"
  hash-secret: "${VNPAY_HASH_SECRET:TESTSECRET}"
  payment-url: "${VNPAY_PAYMENT_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}"
  query-url: "${VNPAY_QUERY_URL:sandbox.vnpayment.vn}"
  return-url: "${VNPAY_RETURN_URL:http://localhost:8080/v1/payments/vnpay/callback}"
  ipn-url: "${VNPAY_IPN_URL:http://localhost:8080/v1/payments/vnpay/ipn}"
  version: "2.1.0"
  command: "pay"
  order-type: "other"
  currency-code: "VND"
  locale: "vn"
  secure-hash-type: "SHA512"
  timeout-minutes: 15

# Application-specific configuration for local development
application:
  client-url: "${CLIENT_URL:http://localhost:3000}"
  authorize-ignored:
    methods:
      get:
        - "/swagger-ui/**"
        - "/swagger-ui.html"
        - "/v3/api-docs/**"
        - "/v3/api-docs"
        - "/swagger-resources/**"
        - "/webjars/**"
        - "/actuator/health"
        - "/actuator/**"
        - "/v1/payments/vnpay/callback"
        - "/v1/listings/**"
        - "/v1/addresses/**"
        - "/v1/memberships/packages"
        - "/v1/memberships/packages/**"
      post:
        - "/v1/auth/**"
        - "/v1/users"
        - "/v1/admins"
        - "/v1/payments/vnpay/ipn"

# Enable debug logging for authentication
logging:
  level:
    com.smartrent.config.security: DEBUG
    com.smartrent.service.authentication: DEBUG
    org.springframework.security: DEBUG